version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healthcare_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

#  backend:
#    build: ./
#    depends_on:
#      - db
#    environment:
#      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=healthcare_dev;Username=postgres;Password=postgres
#      - Jwt__Key=dev_secret_change_me
#    ports:
#      - "5000:5000"

#  frontend:
#    build: ../frontend
#    ports:
#      - "5173:5173"
#    depends_on:
#      - backend

volumes:
  pgdata: